Repository OpenEnergyPlatform/oemetadata, pull requests merged in 2024-10, with the labels that each got.

#156 Remove hkip keys #138
  metadata/v200_draft/build_source/schemas/provenance.json
Labels: wontfix

#157 Update the contributors section #137 #142 #151
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/provenance.json
  metadata/v200_draft/metadata_key_description.md
Labels: enhancement

#155 Add embargo period to general keys #140
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/general.json
  metadata/v200_draft/metadata_key_description.md
Labels: enhancement, SIROP

#160 Specify the mandatory fields to the json schema
  CHANGELOG.md
  metadata/v200_draft/README.md
  metadata/v200_draft/build_source/schemas/general.json
  metadata/v200_draft/build_source/schemas/general_collection.json
  metadata/v200_draft/build_source/schemas/resource.json
Labels: documentation, enhancement

#161 Add a key to make fields (columns) nullable
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/resource.json
  metadata/v200_draft/metadata_key_description.md
Labels: documentation, enhancement

#162 Add key copyrightStatement to sources #127
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/sources.json
  metadata/v200_draft/metadata_key_description.md
Labels: documentation, enhancement

#163 Remove all additionalProperties constraint #132
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/context.json
  metadata/v200_draft/build_source/schemas/general.json
  metadata/v200_draft/build_source/schemas/json_ld.json
  metadata/v200_draft/build_source/schemas/licences.json
  metadata/v200_draft/build_source/schemas/meta.json
  metadata/v200_draft/build_source/schemas/provenance.json
  metadata/v200_draft/build_source/schemas/resource.json
  metadata/v200_draft/build_source/schemas/review.json
  metadata/v200_draft/build_source/schemas/sources.json
  metadata/v200_draft/build_source/schemas/spatial.json
  metadata/v200_draft/build_source/schemas/temporal.json
Labels: bug

#164 Update profile to type table #148
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/resource.json
  metadata/v200_draft/metadata_key_description.md
Labels: documentation, enhancement

#165 Bugfix duplicate names in resources #152
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/general.json
  metadata/v200_draft/build_source/schemas/resource.json
  metadata/v200_draft/metadata_key_description.md
Labels: bug

#166 Add explicit json types #146
  CHANGELOG.md
  metadata/v200_draft/build_source/schemas/general.json
  metadata/v200_draft/build_source/schemas/general_collection.json
  metadata/v200_draft/build_source/schemas/licences.json
  metadata/v200_draft/build_source/schemas/meta.json
  metadata/v200_draft/build_source/schemas/provenance.json
Labels: documentation, enhancement

#159 Update and add keys for Linked Data #158
  CHANGELOG.md
  metadata/v200_draft/build_source/schema_structure.json
  metadata/v200_draft/build_source/schemas/json_ld.json
  metadata/v200_draft/build_source/schemas/linked_data.json
  metadata/v200_draft/build_source/schemas/meta.json
  metadata/v200_draft/metadata_key_description.md
Labels: documentation, enhancement

#167 Update links in context.json and example.json for all versions
  CHANGELOG.md
  metadata/v130/schema.json
  metadata/v140/schema.json
  metadata/v141/schema.json
  metadata/v150/example.json
  metadata/v150/schema.json
  metadata/v151/example.json
  metadata/v152/example.json
  metadata/v160/example.json
  metadata/v160/schema.json
  metadata/v200_draft/schema.json
  tests/metadata/v130/test_schema.py
  tests/metadata/v140/test_schema.py
  tests/metadata/v141/test_schema.py
  tests/metadata/v150/test_schema.py
  tests/metadata/v160/test_schema.py
  tests/metadata/v200/test_schema.py
Labels: bug, documentation

#168 Refactor version to v20 (2.0) in all files #21
  CHANGELOG.md
  metadata/latest/build_source/schemas/context.json
  metadata/latest/build_source/schemas/contribution.json
  metadata/latest/build_source/schemas/general.json
  metadata/latest/build_source/schemas/json_ld.json
  metadata/latest/build_source/schemas/licences.json
  metadata/latest/build_source/schemas/meta.json
  metadata/latest/build_source/schemas/resources.json
  metadata/latest/build_source/schemas/review.json
  metadata/latest/build_source/schemas/sources.json
  metadata/latest/build_source/schemas/spatial.json
  metadata/latest/build_source/schemas/temporal.json
  metadata/latest/build_source/scripts/resolve_schema_refs.py
  metadata/v20/README.md
  metadata/v20/__init__.py
  metadata/v20/build_source/schema_structure.json
  metadata/v20/build_source/schemas/collection.json
  metadata/v20/build_source/schemas/context.json
  metadata/v20/build_source/schemas/general.json
  metadata/v20/build_source/schemas/licences.json
  metadata/v20/build_source/schemas/linked_data.json
  metadata/v20/build_source/schemas/meta.json
  metadata/v20/build_source/schemas/provenance.json
  metadata/v20/build_source/schemas/resource.json
  metadata/v20/build_source/schemas/review.json
  metadata/v20/build_source/schemas/sources.json
  metadata/v20/build_source/schemas/spatial.json
  metadata/v20/build_source/schemas/temporal.json
  metadata/v20/build_source/scripts/generate_example_from_schema.py
  metadata/v20/build_source/scripts/generate_template_from_schema.py
  metadata/v20/build_source/scripts/resolve_schema_refs.py
  metadata/v20/context.json
  metadata/v20/example.json
  metadata/v20/example.py
  metadata/v20/metadata_key_description.md
  metadata/v20/schema.json
  metadata/v20/schema.py
  metadata/v20/template.json
  metadata/v20/template.py
  tests/metadata/v20/test_example.py
  tests/metadata/v20/test_schema.py
  tests/metadata/v20/test_template.py
Labels: documentation, enhancement

#170 Add key topics to general #169
  CHANGELOG.md
  metadata/v20/build_source/schemas/general.json
  metadata/v20/metadata_key_description.md
Labels: enhancement

#175 Bugfix 144 bughunt
  CHANGELOG.md
  metadata/v20/build_source/schema_structure.json
  metadata/v20/build_source/schemas/collection.json
  metadata/v20/build_source/schemas/context.json
  metadata/v20/build_source/schemas/general.json
  metadata/v20/build_source/schemas/licences.json
  metadata/v20/build_source/schemas/meta.json
  metadata/v20/build_source/schemas/properties.json
  metadata/v20/build_source/schemas/provenance.json
  metadata/v20/build_source/schemas/review.json
  metadata/v20/build_source/schemas/sources.json
  metadata/v20/build_source/schemas/spatial.json
  metadata/v20/build_source/schemas/temporal.json
  metadata/v20/metadata_key_description.md
Labels: bug, documentation, enhancement

#176 Include feedback for linkedData section #172
  CHANGELOG.md
  metadata/v20/build_source/schemas/linked_data.json
  metadata/v20/metadata_key_description.md
Labels: bug

#177 Feature-152-fix-bugs-and-enhance-implementation
  CHANGELOG.md
  metadata/latest/build_source/main_schema.json
  metadata/latest/build_source/schemas/licences.json
  metadata/v20/build_source/schema_structure.json
  metadata/v20/build_source/schemas/licenses.json
  metadata/v20/build_source/scripts/__init__.py
  metadata/v20/build_source/scripts/generate_example_from_schema.py
  metadata/v20/build_source/scripts/generate_template_from_schema.py
  metadata/v20/build_source/scripts/resolve_schema_refs.py
  metadata/v20/build_source/scripts/settings.py
Labels: bug, documentation

#179 Feature-178-enhance-spatial-section
  CHANGELOG.md
  metadata/v20/build_source/schemas/spatial.json
  metadata/v20/metadata_key_description.md
Labels: documentation, enhancement

#180 Feature-152-fix-schema-ref-resolve
  CHANGELOG.md
  metadata/v20/build_source/README.md
  metadata/v20/build_source/scripts/generate_example_from_schema.py
  metadata/v20/build_source/scripts/generate_template_from_schema.py
  metadata/v20/build_source/scripts/resolve_schema_refs.py
  metadata/v20/example.json
  metadata/v20/schema.json
  metadata/v20/template.json
  requirements.txt
Labels: enhancement

#183 Move linkedData keys to the top of the resource #181
  CHANGELOG.md
  metadata/v20/build_source/schema_structure.json
  metadata/v20/example.json
  metadata/v20/metadata_key_description.md
  metadata/v20/schema.json
  metadata/v20/template.json
Labels: documentation, enhancement

#185 Update repo structure #120
  .github/ISSUE_TEMPLATE/issue_template_bug.md
  .github/pull_request_template.md
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.txt
  README.md
  README.rst
  USERS.cff
  metadata/v20/build_source/README.md
Labels: documentation

#184 Add basic documentation with MKdocs
  .github/workflows/gh-pages.yml
  CHANGELOG.md
  docs/code/index.md
  docs/code/install/index.md
  docs/code/style/index.md
  docs/css/extra.css
  docs/development/collaboration/citation.md
  docs/development/collaboration/code_of_conduct.md
  docs/development/collaboration/contributing.md
  docs/development/collaboration/index.md
  docs/development/collaboration/license.md
  docs/development/collaboration/users.md
  docs/development/documentation/index.md
  docs/development/git/gitignore.md
  docs/development/git/index.md
  docs/development/git/test-driven-developement-workflow.md
  docs/development/release/index.md
  docs/img/OpenEnergyFamily_Logo_OEMetadata_white.png
  docs/img/logo_oefamily_small.png
  docs/img/logo_rli_small.png
  docs/index.md
  docs/metadata/index.md
  docs/metadata/metadata_key_description.md
  mkdocs.yml
  requirements-docs.txt
Labels: documentation, enhancement

#195 Add a key description to collection and update badges #190
  CHANGELOG.md
  metadata/v20/build_source/schemas/collection.json
  metadata/v20/metadata_key_description.md
Labels: documentation, enhancement

#191 Add 'publisher' to section 'context' #187
  CHANGELOG.md
  metadata/v20/build_source/schemas/context.json
  metadata/v20/metadata_key_description.md
Labels: documentation, enhancement

#193 Add 'authors' to section 'sources' #188
  CHANGELOG.md
  metadata/v20/build_source/schemas/sources.json
  metadata/v20/build_source/schemas/spatial.json
  metadata/v20/build_source/schemas/temporal.json
  metadata/v20/metadata_key_description.md
Labels: documentation, enhancement

#194 Add year to section sources #189
  CHANGELOG.md
  metadata/v20/build_source/schemas/sources.json
  metadata/v20/metadata_key_description.md
Labels: documentation, enhancement

#198 Add mappings to documentation #144
  .github/ISSUE_TEMPLATE/issue_template_release.md
  CHANGELOG.md
  RELEASE_PROCEDURE.md
  docs/metadata/index.md
  docs/metadata/metadata_mappings.md
  mkdocs.yml
Labels: documentation

#199 Add issue template for user kudos #144
  .github/ISSUE_TEMPLATE/issue_template_user_kudos.md
  CHANGELOG.md
Labels: documentation
