Repository OpenEnergyPlatform/oemetadata, pull requests merged in 2025-01, with the labels that each got.

#242 Improve documentation #128
  CHANGELOG.md
  README.rst
  RELEASE_PROCEDURE.md
  REUSE.toml
  docs/index.md
  metadata/v2/v20/build_source/scripts/example/contributors.json
  metadata/v2/v20/metadata_key_description.md
  mkdocs.yml
  setup.py
Labels: type: enhancement ⚙️, priority: critical 🔥, part: backend 🧱, status: completed ✔️

#243 Improve documentation #204
  .github/workflows/documentation.yml
  .github/workflows/gh-pages.yml
  .github/workflows/publish_pypi.yml
  .github/workflows/publish_testpypi.yml
  .github/workflows/reuse.yml
  CHANGELOG.md
  docs/development/release/index.md
  docs/extra.css
  docs/metadata/metadata_key_description.md
  metadata/v2/v20/build_source/schemas/review.json
  metadata/v2/v20/example.json
  metadata/v2/v20/schema.json
  mkdocs.yml
  requirements-docs.txt
Labels: type: enhancement ⚙️, priority: high ⚡, part: backend 🧱, status: completed ✔️

#246 Move the `@context` to dataset level #245
  CHANGELOG.md
  docs/metadata/metadata_key_description.md
  metadata/v2/v20/build_source/schema_structure.json
  metadata/v2/v20/build_source/schemas/dataset.json
  metadata/v2/v20/build_source/schemas/general.json
  metadata/v2/v20/build_source/schemas/linked_data.json
  metadata/v2/v20/build_source/scripts/example/fields.json
  metadata/v2/v20/example.json
  metadata/v2/v20/metadata_key_description.md
  metadata/v2/v20/schema.json
  metadata/v2/v20/template.json
Labels: type: bug 🐛, priority: critical 🔥, part: backend 🧱, status: completed ✔️

#247 Move and sort imports #244
  .github/workflows/documentation.yml
  CHANGELOG.md
  README.rst
  requirements-docs.txt
  requirements.txt
Labels: type: enhancement ⚙️, priority: low 🦥, part: backend 🧱, status: completed ✔️

#234 Extend the context file to get better RDF coverage
  .gitignore
  CHANGELOG.md
  docs/metadata/metadata_key_description.md
  metadata/v2/v20/build_source/schemas/general.json
  metadata/v2/v20/build_source/schemas/provenance.json
  metadata/v2/v20/build_source/schemas/temporal.json
  metadata/v2/v20/context.json
  metadata/v2/v20/metadata_key_description.md
  requirements.txt
  tests/metadata/v2/v20/test_context.py
Labels: priority: critical 🔥, part: backend 🧱, type: feature 🛠, status: active 🚧
